# Generated by Django 4.2.29 on 2026-03-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.AddField(
            model_name='libro',
            name='unidades',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='unidades_diponibles',
            field=models.IntegerField(default=1),
        ),
    ]
