# Generated by Django 4.2.29 on 2026-04-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='unidades_diponibles',
            new_name='unidades_disponibles',
        ),
    ]
