# Generated by Django 4.2.29 on 2026-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_unidades_diponibles_libro_unidades_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='en_multa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='monto_multa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
