# Generated by Django 4.2.29 on 2026-04-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_libro_en_multa_libro_monto_multa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='monto_multa',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='monto_multa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
