# Generated by Django 4.2.29 on 2026-04-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_remove_libro_monto_multa_prestamo_monto_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
