# Generated by Django 4.2.30 on 2026-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='renovacion_consumida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
