# Generated by Django 4.2.30 on 2026-07-17 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0008_prestamo_renovacion_consumida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lector', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
